### ISSUE TITLE
Editor blank when special chars in text boxes

### ISSUE THREAD

**Issue by greatestview** [palasthotel/grid#459]
When you insert a text into container prolog in code view with a questionmark inside, a JavaScript error is thrown. If that text is stored into the database, the error prevents the Grid vom appearing in editor view, editing is not possible any more.

Example text for container prolog in code view for reproduction: `Is this a test?`

![Bildschirmfoto 2020-01-16 um 12 06 31](https://user-images.githubusercontent.com/2060276/72521588-02012e80-385c-11ea-8192-1d483a67110c.png)

I think this is an escaping issue and affects probably also epilog and other text fields and boxes.

@EdwardBock, could you have a look into this?

**Comment by EdwardBock** [comment]
Lets have a look

**Comment by EdwardBock** [comment]
@greatestview 

We use `jQuery(prolog).text()` to strip html from prolog and epilog. But when there is a question mark without wrapping html tags that is killing jquery because it wants to interprete it somehow.

Fixed it by wrapping the contents with a `div` tag. But be careful because even if you save epilog or prolog content with source code without html tags next time you open the box editor it will be auto wrapped by ckeditor. ☝️

**Comment by EdwardBock** [comment]
Please check with next release and close if it's ok

**Comment by greatestview** [comment]
Works, thank you!
